AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Rust Runtime SAM Example"

Parameters:
  RustLayerArn:
    Type: String
    Description: ARN of the published Rust Lambda layer for your region/account

Resources:
  RustExample:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: hello/
      Handler: handler
      Runtime: provided.al2023
      Layers:
        - !Ref RustLayerArn
