AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "GraalPy Runtime SAM Example"

Parameters:
  GraalPyLayerArn:
    Type: String
    Description: ARN of the published GraalPy Lambda layer for your region/account

Resources:
  GraalPyExample:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: hello/
      Handler: hello.handler
      Runtime: provided.al2023
      Layers:
        - !Ref GraalPyLayerArn
